server:
  port: 8081

spring:
  application:
    name: admin-system
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/admin?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
      username: root
      password:
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  freemarker:
    enabled: true
    charset: UTF-8
    suffix: .html
    check-template-location: true
    template-loader-path: ["classpath:/templates/"]
    request-context-attribute: ctx
    content-type: text/html;charset=UTF-8
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    settings:
      locale: zh_CN
      datetime_format: yyyy-MM-dd HH:mm:ss
      date_format: yyyy-MM-dd
      template_update_delay: 10
      number_format: #.##
  main:
    allow-bean-definition-overriding: true
  redis:
    host: localhost
    port: 6379

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/mybatis-config.xml
  type-aliases-package: com.chanpion.admin.system.entity

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

shiro:
  web:
    enabled: true
  loginUrl: /login
  unauthorizedUrl: /login
  successUrl: /index

logging:
  level:
    root: info

